name: parking_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.3.4
  google_maps_flutter: ^2.10.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  dropdown_button2: ^2.0.0
  parking_shared:
    path: ../parking_shared
  firebase_repositories:
    path: ../firebase_repositories
  flutter_bloc: ^8.1.0
  equatable: ^2.0.7
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  cloud_firestore: ^5.6.2
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  objectbox_generator: ^4.0.3

flutter:
  uses-material-design: true
