name: parking_shared
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.3
  json_annotation: ^4.8.0
  shelf_router: ^1.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  objectbox_generator: ^4.0.3

flutter:
  uses-material-design: true
